x-requirements-image: &requirements-image
  image: ${COSMOSYS_REQ_IMAGE:-cosmobots/cosmosys-req:cee9592-c58f52f-redmine-7.0.1}
  build:
    target: cosmosys_requirements
    args:
      COSMOSYS_REQ_REVISION: ${COSMOSYS_REQ_REVISION:-c58f52ff9faabb4f9acb2c77a91040599bb892ca}

services:
  migrate:
    <<: *requirements-image

  redmine:
    <<: *requirements-image
