#!/bin/sh
set -eu

root_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
shared_env=${COSMOSYS_SHARED_DB_ENV_FILE:-"$root_dir/shared-db/.env"}

usage() {
  echo "Usage: $0 INSTANCE_NAME INSTANCE_ENV_FILE [HTTP_PORT]" >&2
  echo "Creates the instance role and database on the shared PostgreSQL server" >&2
  echo "and writes a new environment file for the instance." >&2
}

instance=${1:-}
instance_env=${2:-}
http_port=${3:-0}

if [ -z "$instance" ] || [ -z "$instance_env" ]; then
  usage
  exit 2
fi

case "$instance" in
  [a-z]*) ;;
  *)
    echo "INSTANCE_NAME must start with a lowercase letter" >&2
    exit 2
    ;;
esac
case "$instance" in
  *[!a-z0-9_]*)
    echo "INSTANCE_NAME may only contain a-z, 0-9 and _" >&2
    exit 2
    ;;
esac
if [ "${#instance}" -gt 40 ]; then
  echo "INSTANCE_NAME must not exceed 40 characters" >&2
  exit 2
fi
case "$http_port" in
  ''|*[!0-9]*)
    echo "HTTP_PORT must be a number" >&2
    exit 2
    ;;
esac

if [ -e "$instance_env" ]; then
  echo "Refusing to overwrite $instance_env" >&2
  exit 1
fi
if [ ! -f "$shared_env" ]; then
  echo "Missing $shared_env; copy shared-db/.env.example and set its password." >&2
  exit 1
fi

# Shell variables take precedence over the shared environment file, as in Compose.
shared_setting() {
  eval "shared_value=\${$1:-}"
  if [ -z "$shared_value" ]; then
    shared_value=$(sed -n "s/^$1=//p" "$shared_env" | tail -n 1)
  fi
  printf '%s' "${shared_value:-$2}"
}

shared_compose() {
  if [ -n "${COSMOSYS_SHARED_DB_PROJECT:-}" ]; then
    set -- -p "$COSMOSYS_SHARED_DB_PROJECT" "$@"
  fi
  docker compose --env-file "$shared_env" -f "$root_dir/shared-db/compose.yml" "$@"
}

admin_user=$(shared_setting COSMOSYS_DB_ADMIN_USER postgres)
db_host=$(shared_setting COSMOSYS_DB_HOST csys-db)
db_network=$(shared_setting COSMOSYS_DB_NETWORK csys_db)
connection_limit=$(shared_setting COSMOSYS_DB_CONNECTION_LIMIT 20)
role="csys_$instance"

case "$connection_limit" in
  ''|*[!0-9]*)
    echo "COSMOSYS_DB_CONNECTION_LIMIT must be a number" >&2
    exit 2
    ;;
esac

existing=$(shared_compose exec -T postgres psql -U "$admin_user" -d postgres -tAc \
  "SELECT (SELECT count(*) FROM pg_roles WHERE rolname = '$role') + (SELECT count(*) FROM pg_database WHERE datname = '$role')")
if [ "$existing" != 0 ]; then
  echo "Role or database $role already exists on the shared server" >&2
  exit 1
fi

db_password=$(openssl rand -hex 32)
secret_key_base=$(openssl rand -hex 64)
admin_password=$(openssl rand -hex 16)

temporary_env="$instance_env.$$.tmp"
umask 077
cat >"$temporary_env" <<EOF
# cosmoSys instance $instance on the shared PostgreSQL server.
# Generated by scripts/provision-shared-db.sh; keep it outside source control.
COMPOSE_PROJECT_NAME=csys_$instance
COSMOSYS_DB_MODE=shared
COSMOSYS_DB_HOST=$db_host
COSMOSYS_DB_NETWORK=$db_network
POSTGRES_DB=$role
POSTGRES_USER=$role
POSTGRES_PASSWORD=$db_password
REDMINE_SECRET_KEY_BASE=$secret_key_base
COSMOSYS_INITIAL_ADMIN_PASSWORD=$admin_password
COSMOSYS_HTTP_PORT=$http_port
EOF

# The password travels on standard input, never on a command line.
if ! printf '%s\n' \
  '\set ON_ERROR_STOP on' \
  "CREATE ROLE $role LOGIN PASSWORD '$db_password' CONNECTION LIMIT $connection_limit;" \
  "CREATE DATABASE $role OWNER $role;" \
  "REVOKE CONNECT, TEMPORARY ON DATABASE $role FROM PUBLIC;" |
  shared_compose exec -T postgres psql -U "$admin_user" -d postgres -q; then
  rm -f -- "$temporary_env"
  echo "Provisioning failed; check whether role $role exists and drop it before retrying." >&2
  exit 1
fi

mv -- "$temporary_env" "$instance_env"

cat <<EOF
Provisioned $role on the shared PostgreSQL server.
Instance environment file: $instance_env

From $root_dir, start the instance with:
  docker compose --env-file $instance_env -f compose.yml -f compose.shared-db.yml up -d
The deployment scripts use it through COSMOSYS_ENV_FILE=$instance_env.
EOF
