#!/bin/sh
set -eu

root_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
shared_env=${COSMOSYS_SHARED_DB_ENV_FILE:-"$root_dir/shared-db/.env"}
proxy_env=${COSMOSYS_PROXY_ENV_FILE:-"$root_dir/proxy/.env"}

usage() {
  cat >&2 <<EOF
Usage: $0 [--http-port PORT] [--hostname HOST [--tls EMAIL|internal]]
       INSTANCE_NAME INSTANCE_ENV_FILE

Creates the instance role and database on the shared PostgreSQL server and
writes a new environment file for the instance. With --hostname the instance
is also published through the shared reverse proxy; --tls defaults to
COSMOSYS_PROXY_TLS from the shell or proxy/.env.
EOF
}

http_port=0
public_host=
proxy_tls=
while [ "$#" -gt 0 ]; do
  case "$1" in
    --http-port|--hostname|--tls)
      if [ "$#" -lt 2 ]; then
        usage
        exit 2
      fi
      case "$1" in
        --http-port) http_port=$2 ;;
        --hostname) public_host=$2 ;;
        --tls) proxy_tls=$2 ;;
      esac
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    -*)
      echo "Unknown option: $1" >&2
      usage
      exit 2
      ;;
    *)
      break
      ;;
  esac
done

if [ "$#" -ne 2 ]; then
  usage
  exit 2
fi
instance=$1
instance_env=$2

case "$instance" in
  [a-z]*) ;;
  *)
    echo "INSTANCE_NAME must start with a lowercase letter" >&2
    exit 2
    ;;
esac
case "$instance" in
  *[!a-z0-9_]*)
    echo "INSTANCE_NAME may only contain a-z, 0-9 and _" >&2
    exit 2
    ;;
esac
if [ "${#instance}" -gt 40 ]; then
  echo "INSTANCE_NAME must not exceed 40 characters" >&2
  exit 2
fi
case "$http_port" in
  ''|*[!0-9]*)
    echo "--http-port must be a number" >&2
    exit 2
    ;;
esac
if [ -n "$proxy_tls" ] && [ -z "$public_host" ]; then
  echo "--tls requires --hostname" >&2
  exit 2
fi

# Shell variables take precedence over environment files, as in Compose.
file_setting() {
  eval "file_value=\${$2:-}"
  if [ -z "$file_value" ] && [ -f "$1" ]; then
    file_value=$(sed -n "s/^$2=//p" "$1" | tail -n 1)
  fi
  printf '%s' "${file_value:-$3}"
}

if [ -n "$public_host" ]; then
  case "$public_host" in
    ''|*[!a-z0-9.-]*|.*|*.|*..*)
      echo "--hostname must be a lowercase DNS name" >&2
      exit 2
      ;;
  esac
  if [ -z "$proxy_tls" ]; then
    proxy_tls=$(file_setting "$proxy_env" COSMOSYS_PROXY_TLS '')
  fi
  case "$proxy_tls" in
    internal) ;;
    *[!A-Za-z0-9@._+-]*|'')
      echo "Pass --tls with an ACME e-mail address or internal, or set COSMOSYS_PROXY_TLS" >&2
      exit 2
      ;;
    ?*@?*.?*) ;;
    *)
      echo "--tls must be an ACME e-mail address or internal" >&2
      exit 2
      ;;
  esac
  proxy_network=$(file_setting "$proxy_env" COSMOSYS_PROXY_NETWORK caddy_proxy)
fi

if [ -e "$instance_env" ]; then
  echo "Refusing to overwrite $instance_env" >&2
  exit 1
fi
if [ ! -f "$shared_env" ]; then
  echo "Missing $shared_env; copy shared-db/.env.example and set its password." >&2
  exit 1
fi

shared_compose() {
  if [ -n "${COSMOSYS_SHARED_DB_PROJECT:-}" ]; then
    set -- -p "$COSMOSYS_SHARED_DB_PROJECT" "$@"
  fi
  docker compose --env-file "$shared_env" -f "$root_dir/shared-db/compose.yml" "$@"
}

admin_user=$(file_setting "$shared_env" COSMOSYS_DB_ADMIN_USER postgres)
db_host=$(file_setting "$shared_env" COSMOSYS_DB_HOST csys-db)
db_network=$(file_setting "$shared_env" COSMOSYS_DB_NETWORK csys_db)
connection_limit=$(file_setting "$shared_env" COSMOSYS_DB_CONNECTION_LIMIT 20)
role="csys_$instance"

case "$connection_limit" in
  ''|*[!0-9]*)
    echo "COSMOSYS_DB_CONNECTION_LIMIT must be a number" >&2
    exit 2
    ;;
esac

existing=$(shared_compose exec -T postgres psql -U "$admin_user" -d postgres -tAc \
  "SELECT (SELECT count(*) FROM pg_roles WHERE rolname = '$role') + (SELECT count(*) FROM pg_database WHERE datname = '$role')")
if [ "$existing" != 0 ]; then
  echo "Role or database $role already exists on the shared server" >&2
  exit 1
fi

db_password=$(openssl rand -hex 32)
secret_key_base=$(openssl rand -hex 64)
admin_password=$(openssl rand -hex 16)

temporary_env="$instance_env.$$.tmp"
umask 077
{
  echo "# cosmoSys instance $instance."
  echo "# Generated by scripts/provision-instance.sh; keep it outside source control."
  echo "COMPOSE_PROJECT_NAME=csys_$instance"
  echo "COSMOSYS_DB_MODE=shared"
  echo "COSMOSYS_DB_HOST=$db_host"
  echo "COSMOSYS_DB_NETWORK=$db_network"
  echo "POSTGRES_DB=$role"
  echo "POSTGRES_USER=$role"
  echo "POSTGRES_PASSWORD=$db_password"
  echo "REDMINE_SECRET_KEY_BASE=$secret_key_base"
  echo "COSMOSYS_INITIAL_ADMIN_PASSWORD=$admin_password"
  echo "COSMOSYS_HTTP_PORT=$http_port"
  if [ -n "$public_host" ]; then
    echo "COSMOSYS_PROXY_MODE=shared"
    echo "COSMOSYS_HOSTNAME=$public_host"
    echo "COSMOSYS_PROXY_TLS=$proxy_tls"
    echo "COSMOSYS_PROXY_NETWORK=$proxy_network"
  fi
} >"$temporary_env"

# The password travels on standard input, never on a command line.
if ! printf '%s\n' \
  '\set ON_ERROR_STOP on' \
  "CREATE ROLE $role LOGIN PASSWORD '$db_password' CONNECTION LIMIT $connection_limit;" \
  "CREATE DATABASE $role OWNER $role;" \
  "REVOKE CONNECT, TEMPORARY ON DATABASE $role FROM PUBLIC;" |
  shared_compose exec -T postgres psql -U "$admin_user" -d postgres -q; then
  rm -f -- "$temporary_env"
  echo "Provisioning failed; check whether role $role exists and drop it before retrying." >&2
  exit 1
fi

mv -- "$temporary_env" "$instance_env"

compose_files="-f compose.yml -f compose.shared-db.yml"
if [ -n "$public_host" ]; then
  compose_files="$compose_files -f compose.proxy.yml"
fi

cat <<EOF
Provisioned $role on the shared PostgreSQL server.
Instance environment file: $instance_env

From $root_dir, start the instance with:
  docker compose --env-file $instance_env $compose_files up -d
The deployment scripts use it through COSMOSYS_ENV_FILE=$instance_env.
EOF
